### ISSUE TITLE
Usage of OCPI library

### ISSUE THREAD

**Issue by susanthomasv99** [Llocer/llocer_ocpi#1]
Hi, I'm trying to test the location modules example using this library. But I'm having trouble with understanding the main server code which I have to run. What do I have to do to test this library?

**Comment by Llocer** [comment]
Hi,

Thanks for your interest in these librarians.

You have full-functionality examples of OCPI nodes at librarian [llocer_ev_examples](https://github.com/Llocer/llocer_ev_examples). In particular, there are examples of location module as [sender](https://github.com/Llocer/llocer_ev_examples/blob/master/src/main/java/com/llocer/ev/example/OcpiTestLocationSender.java) and location module as [receiver](https://github.com/Llocer/llocer_ev_examples/blob/master/src/main/java/com/llocer/ev/example/OcpiTestLocationReceiver.java).

The main page of this librarian contains a description of the examples.

Do not hesitate to ask any doubt.

Kind regards.

**Comment by susanthomasv99** [comment]
Thank you for replying. Can I run these sender and receiver modules independently? It shows an error that main method is missing. Also, Any API implementation required to test this?

**Comment by Llocer** [comment]
Yes, sender and receiver are independent modules.

Can I ask which servlet container are you using? These examples have been tested using Tomcat.

You can post the text of the error you refer.

**Comment by susanthomasv99** [comment]
Hi,
I'm looking to implement OCPI node to node communication between two
parties without using any hubs. I came across your library and that's what
I'm looking for. But I'm completely new to Java and I'm finding it
difficult to understand how to test this library. Can you please give me
the steps I need to follow? I'm not using any servlet containers now.
Anything else required to test this?

**Comment by Llocer** [comment]
Hi,

OCPI protocol is based on HTTP, being OCPI nodes an specialization of HTTP servers. As you know, the usual way to implement in Java a HTTP server is implementing a servlet and run it in a servlet container as Tomcat.

The servlet implementation is totally included in this librarian ([here](https://github.com/Llocer/llocer_ocpi/tree/master/src/main/java/com/llocer/ev/ocpi/server)). Thus, usual steps will be:

- create in your preferred IDE the maven projects for the librarians and compile them.
- create the war file that includes all the necessary jar files. 
- configure your servlet container to run previous war
- configure your network to accept HTTP request to the address of the servlet container.

**Comment by susanthomasv99** [comment]
Thank you for explaining the steps in detail. I will try it out
